# Helper functions for the bot
def calculate_arbitrage_opportunity():
    # ...code to calculate arbitrage opportunity...

def adjust_gas_price():
    # ...code to adjust gas price...

# ...rest of the code...